api:
  prefix: api/v1
baseUrl: http://localhost:8088
jwt:
  expiration: 2592000
  secretKey: Nq1t86/HZmr1Z8rFY/Smm3JUQxtUnHeahOHs+A5BVvk=
server:
  port: 8088
spring:
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/WebBanHang?useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  messages:
    basename: i18n/messages
    default-locale: en
    encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret: 
            redirect-uri: '{baseUrl}/login/oauth2/code/google'
            scope: profile,email
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


